version: '3.8'

services:
  # Neo4j Database for Knowledge Graph
  neo4j:
    image: neo4j:5.8
    container_name: mosdac_neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - mosdac_network

  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: mosdac_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mosdac_ai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mosdac_network

  # Redis for Caching
  redis:
    image: redis:7-alpine
    container_name: mosdac_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mosdac_network

  # FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: mosdac_backend
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mosdac_ai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
      - ./models:/app/models
    depends_on:
      - neo4j
      - postgres
      - redis
    networks:
      - mosdac_network

  # React Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: mosdac_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    depends_on:
      - backend
    networks:
      - mosdac_network

volumes:
  neo4j_data:
  neo4j_logs:
  postgres_data:
  redis_data:

networks:
  mosdac_network:
    driver: bridge